Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/bin/analyze
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy
accounting_group = group_atlas.boulder


Arguments = 2 1
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ2_iCent1.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ2_iCent1.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ2_iCent1.err
Queue 1

Arguments = 2 2
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ2_iCent2.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ2_iCent2.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ2_iCent2.err
Queue 1

Arguments = 2 3
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ2_iCent3.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ2_iCent3.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ2_iCent3.err
Queue 1

Arguments = 3 1
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ3_iCent1.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ3_iCent1.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ3_iCent1.err
Queue 1

Arguments = 3 2
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ3_iCent2.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ3_iCent1.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ3_iCent2.err
Queue 1

Arguments = 3 3
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ3_iCent3.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ3_iCent3.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ3_iCent3.err
Queue 1

Arguments = 4 1
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ4_iCent1.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ4_iCent1.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ4_iCent1.err
Queue 1

Arguments = 4 2
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ4_iCent2.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ4_iCent2.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ4_iCent2.err
Queue 1

Arguments = 4 3
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/logs/analyze_iPtZ4_iCent3.log
Output = /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/outputs/PullStudy/analyze_iPtZ4_iCent3.out
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/PullStudy/errors/analyze_iPtZ4_iCent3.err
Queue 1

